ENGLISH_CENTRAL_FAMILY = {
    "en_central_family_1": ['en'],
    "en_central_family_2": ['es'],
    "en_central_family_3": ['fr'],
    "en_central_family_4": ['pt'],
    "en_central_family_5": ['de'],
    "en_central_family_6": ['it'],
    "en_central_family_7": ['nl'],
    "en_central_family_8": ['pl'],
    "en_central_family_9": ['ru'],
    "en_central_family_10": ['cs'],
    "en_central_family_11": ['ro'],
    "en_central_family_12": ['sv'],
    "en_central_family_13": ['el'],
    "en_central_family_14": ['hu'],
    "en_central_family_15": ['tr'],
    "en_central_family_16": ['bg'],
    "en_central_family_17": ['fi'],
    "en_central_family_18": ['ar'],
    "en_central_family_19": ['da'],
    "en_central_family_20": ['sl'],
    "en_central_family_21": ['sr'],
    "en_central_family_22": ['sk'],
    "en_central_family_23": ['he'],
    "en_central_family_24": ['hr'],
    "en_central_family_25": ['no'],
    "en_central_family_26": ['id'],
    "en_central_family_27": ['zh'],
    "en_central_family_28": ['et', 'vi'],
    "en_central_family_29": ['lt', 'ja'],
    "en_central_family_30": ['fa', 'lv'],
    "en_central_family_31": ['ca', 'ko'],
    "en_central_family_32": ['uk', 'bs', 'hi'],
    "en_central_family_33": ['sq', 'mk', 'bn', 'ms'],
    "en_central_family_34": ['zhtrad', 'gl', 'th', 'is', 'ta'],
    "en_central_family_35": ['sw', 'mt', 'eu', 'eo', 'tl', 'ml', 'af', 'si'],
    "en_central_family_36": ['ur', 'be', 'ne', 'mr', 'nb', 'ze', 'ka', 'sh', 'az', 'ga', 'te', 'hy', 'mg', 'kk', 'cy',
                             'lb', 'ht', 'ast', 'jv', 'tg', 'km', 'am', 'mn', 'su', 'my', 'so', 'oc', 'xh', 'ha'],
    "en_central_family_37": ['ky', 'ps', 'pa', 'gu', 'nds', 'ku', 'nn', 'fy', 'la', 'kn', 'mi', 'yo', 'br', 'ig',
                             'zhtw', 'sn', 'ny', 'hne', 'jap', 'ceb', 'zu', 'uz', 'lo', 'cx', 'sd', 'wa', 'as', 'se',
                             'mai', 'pes', 'dje', 'pck', 'plt', 'crp', 'kek', 'tt', 'rw', 'csb', 'fil', 'or', 'yi',
                             'wo', 'ug', 'gd', 'ilo', 'hsb', 'dv', 'ss', 'crh', 'simple', 'gv', 'swa', 'tn', 'an',
                             'kab', 'nso', 'ba', 'kbh', 'syr', 'cop', 'chr', 'rom', 'quw', 'cjp', 'dop', 'shi', 'ee',
                             'nhg', 'li', 'amu', 'wal', 'jak', 'usp', 'cni', 'ppk', 'quc', 'mam', 'hbs', 'ch', 'chq',
                             'cak', 'djk', 'cb', 'gbi', 'fur', 'ff', 'bsn', 'ojb', 'agr', 'dik', 'jiv', 'ake', 'acu',
                             'ia', 'lg', 'tk', 'fo', 'om', 'ber', 'dz', 'tmh', 'mhr', 'ln', 'pot', 'ang', 'io', 'kg',
                             'bo', 'sa', 'ns', 'frp', 'ti', 'ckb', 'kw', 'bar', 'arz', 'wae', 'srp', 'os', 'ks', 'sc',
                             'ace', 'shn', 'jbo', 'me', 'arq', 'ts', 'szl', 'gom', 'sco', 'zht', 'kl', 'xho', 'zhs',
                             'toki', 'qu', 'jp', 'mwl', 'ab', 'aa', 'aym', 'som', 'vec', 'zza', 'cv', 'ltg', 'hau',
                             'zhyue', 'bem', 'tlh', 'shs', 'tmp', 'ie', 'pap', 'inh', 'zul', 'cmn', 'prs', 'lmo', 'ara',
                             'lfn', 'ce', 'mlg', 'tet', 'rm', 'lld', 'wuu', 'miq', 'kr', 'ay', 'nan', 'st', 'amh', 'gn',
                             'mus', 'efi', 'mfe', 'av', 'aka', 've', 'scn', 'bi', 'dsb', 'pms', 'ase', 'rn', 'azb',
                             'pmy', 'iu', 'kj', 'co', 'lin', 'gr', 'bam', 'ak', 'ry', 'bh', 'lad', 'nya', 'vo', 'ksh',
                             'xal', 'nap', 'tir', 'fj', 'bua', 'gos', 'rup', 'pan', 'tc', 'orm', 'zsm', 'sml', 'grc',
                             'nus', 'fuv', 'pi', 'din', 'bal', 'lij', 'hil', 'brx', 'bug', 'ful', 'hai', 'cbk', 'cu',
                             'pam', 'mos', 'dtp', 'qd', 'cnh', 'trv', 'avk', 'bnt', 'to', 'kzj', 'swg', 'bm', 'tzl',
                             'zam', 'que', 'orv', 'cho', 'yue', 'kha', 'bho', 'war', 'bzt', 'mad', 'gcf', 'wol', 'nov',
                             'pnb', 'ota', 'nr', 'frm', 'sah', 'swh', 'enm', 'ae', 'kmr', 'yor', 'sgn', 'nst', 'cku',
                             'hrx', 'lzh', 'qa', 'hoc', 'fkv', 'tw', 'vls', 'cat', 'ik', 'prg', 'frr', 'haw', 'tmr',
                             'nv', 'max', 'egl', 'krl', 'ain', 'sjn', 'hup', 'kik', 'ibo', 'gsw', 'pcd', 'got', 'awa',
                             'mh', 'rue', 'qya', 'ldn', 'nah', 'ary', 'sux', 'cr', 'luo', 'stq', 'kin', 'sat', 'luy',
                             'hbo', 'zgh', 'npi', 'zlm', 'min', 'moh', 'hus', 'tpi', 'yaq', 'nog', 'afb', 'nch', 'afh',
                             'sm', 'tpw', 'mww', 'kau', 'evn', 'pdc', 'run', 'lut', 'rif', 'ext', 'dws', 'tz', 'umb',
                             'udm', 'ho', 'drt', 'kv', 'zz', 'fro', 'cycl', 'iba', 'pag', 'thv', 'sgs', 'sma', 'bom',
                             'acm', 'tly', 'xmf', 'apc', 'gbm', 'mo', 'ike', 'ngu', 'hif', 'phn', 'jam', 'pau', 'sdh',
                             'liv', 'lkt', 'mgm', 'ppl', 'niu', 'akl', 'aln', 'dng', 'myv', 'rap', 'shy', 'bvy', 'ood',
                             'quz', 'aoz', 'cdo', 'sot', 'ty', 'bjn', 'na', 'non', 'hak', 'kjh', 'ngt', 'mik', 'kpv',
                             'tvl', 'gan', 'gil', 'koi', 'nlv', 'ady', 'mic', 'sg', 'sz', 'osp', 'izh', 'kam', 'mvv',
                             'iro', 'ofs', 'sna'],
}

X_X_FAMILY_8 = {
    "x_x_family_1": ['fr', 'es', 'en'],
    "x_x_family_2": ['nl', 'tr', 'pl', 'it', 'de', 'pt'],
    "x_x_family_3": ['bg', 'ar', 'ru', 'fa', 'el', 'hu', 'ro', 'cs'],
    "x_x_family_4": ['sk', 'da', 'uk', 'sl', 'he', 'fi', 'id', 'sv', 'vi'],
    "x_x_family_5": ['ko', 'sq', 'hr', 'mk', 'sr', 'zh', 'no', 'bs', 'hi', 'ja'],
    "x_x_family_6": ['eo', 'mt', 'eu', 'sw', 'ta', 'is', 'lv', 'ca', 'th', 'ms', 'zhtrad', 'bn', 'lt',
                     'et'],
    "x_x_family_7": ['ig', 'km', 'ky', 'ps', 'ku', 'tg', 'gv', 'ha', 'yo', 'nb', 'br', 'ss', 'sh', 'ze',
                     'zu', 'nn', 'pa', 'so', 'sn', 'kk', 'my', 'cy', 'mg', 'am', 'xh', 'az', 'ka', 'gu',
                     'mi', 'hy', 'kn', 'te', 'ga', 'gl', 'be', 'mr', 'ur', 'ne', 'si', 'af', 'ml', 'tl'],
    "x_x_family_8": ['iro', 'kam', 'mvv', 'ofs', 'izh', 'ady', 'mic', 'osp', 'sg', 'sz', 'gan', 'gil',
                     'koi', 'nlv', 'tvl', 'kjh', 'mik', 'ngt', 'shy', 'bjn', 'hak', 'na', 'non', 'ty',
                     'aoz', 'cdo', 'quz', 'bvy', 'ood', 'dng', 'myv', 'rap', 'akl', 'aln', 'niu', 'lkt',
                     'liv', 'mgm', 'ppl', 'pau', 'sdh', 'jam', 'hif', 'phn', 'mo', 'ngu', 'ike', 'gbm',
                     'apc', 'xmf', 'acm', 'tly', 'bom', 'sma', 'sgs', 'pag', 'thv', 'iba', 'cycl', 'fro',
                     'zz', 'drt', 'ho', 'udm', 'umb', 'tz', 'dws', 'ext', 'kv', 'rif', 'lut', 'pdc', 'evn',
                     'mww', 'moh', 'tpw', 'afh', 'sm', 'nch', 'afb', 'nog', 'hus', 'tpi', 'yaq', 'min',
                     'luo', 'zlm', 'npi', 'zgh', 'hbo', 'luy', 'sat', 'cr', 'stq', 'ae', 'sux', 'pnb',
                     'ary', 'nah', 'ldn', 'qya', 'rue', 'mh', 'awa', 'got', 'pcd', 'gsw', 'kik', 'hup',
                     'sjn', 'ain', 'cho', 'krl', 'egl', 'max', 'nv', 'tmr', 'haw', 'ik', 'frr', 'prg',
                     'vls', 'tw', 'fkv', 'hoc', 'qa', 'lzh', 'hrx', 'cku', 'nst', 'sgn', 'kmr', 'enm',
                     'swh', 'frm', 'sah', 'nr', 'ota', 'nov', 'mad', 'gcf', 'grc', 'bzt', 'war', 'bho',
                     'kha', 'orv', 'que', 'zam', 'tzl', 'to', 'swg', 'bnt', 'trv', 'kzj', 'bug', 'lij',
                     'sml', 'avk', 'cnh', 'mos', 'hai', 'qd', 'pam', 'dtp', 'bua', 'cu', 'hil', 'brx',
                     'cbk', 'zhyue', 'bal', 'pi', 'din', 'fuv', 'nus', 'bh', 'zsm', 'tc', 'ksh', 'rup',
                     'nap', 'gos', 'fj', 'xal', 'efi', 'vo', 'lad', 'ry', 'pmy', 'kj', 'gr', 'co', 'bm',
                     'ase', 'bi', 'iu', 'pms', 'azb', 'rn', 'hbs', 'dsb', 'av', 'scn', 've', 'miq', 'mfe',
                     'mus', 'mwl', 'nan', 'rm', 'gn', 'lld', 'st', 'wuu', 'kr', 'tet', 'lmo', 'ce', 'ak',
                     'lfn', 'prs', 'cmn', 'pap', 'ber', 'inh', 'bem', 'tmp', 'ie', 'toki', 'shs', 'tlh',
                     'ab', 'cv', 'aa', 'ltg', 'zhs', 'vec', 'zza', 'zht', 'qu', 'kl', 'ilo', 'bar', 'shn',
                     'ay', 'sco', 'szl', 'arz', 'gom', 'arq', 'ts', 'jbo', 'sc', 'ace', 'os', 'ks', 'wae',
                     'ckb', 'frp', 'kw', 'zhtw', 'ti', 'sa', 'ns', 'bo', 'kg', 'ba', 'fo', 'io', 'dz',
                     'mhr', 'ang', 'ln', 'pot', 'tmh', 'om', 'fil', 'ia', 'lg', 'ff', 'tk', 'csb', 'yi',
                     'acu', 'ake', 'cb', 'jiv', 'se', 'dik', 'an', 'tn', 'agr', 'tt', 'kek', 'ojb', 'crp',
                     'pck', 'plt', 'dje', 'pes', 'lb', 'gbi', 'djk', 'cak', 'mai', 'bsn', 'chq', 'quc',
                     'mam', 'ch', 'fur', 'ppk', 'sd', 'cni', 'usp', 'jak', 'wal', 'amu', 'ee', 'lo', 'rw',
                     'nhg', 'shi', 'dop', 'wa', 'cx', 'li', 'cjp', 'rom', 'quw', 'chr', 'cop', 'syr', 'ug',
                     'su', 'kab', 'ceb', 'hsb', 'kbh', 'hne', 'uz', 'nso', 'fy', 'ht', 'wo', 'crh', 'la',
                     'ny', 'or', 'gd', 'oc', 'jv', 'nds', 'mn', 'as', 'ast'],

}
